### PR TITLE
Laravel 8 + add possibility to use multiple middlewares from env

### PR DESCRIPTION
**Pull request by tsekka**
Also changes the way listener is registered in service provider. Old way, the listener was shown as registered but listener did not actually work when mail was sent (email was not saved to db). If it worked before, then there is probably some changes in framework.

### CODE REVIEW

**Comment by dmcbrn** [comment]
Will tackle this in a day or so. You can upgrade to 5.0 to use with Laravel 8.0 in the meantime.

**Comment by dmcbrn** [comment]
@tsekka  One question. Keep in mind I'm not that good with composer and versioning. Is there any reason why this package would not be working through "all" of the Laravel versions? L5+ or any other?

Could we just put all of those into `composer.json` and then just have one version for all L5+ versions. I just realized this as I saw you ad the | in the composer.json.

**Comment by tsekka** [comment]
Hey there
Yeah I didn't notice you had separate version for laravel 8.
It's only worth having separate package versions for different framework versions if there is incompatible changes. I don't think there is anything preventing using the same version from 6 and upwards. Versions below 6 doesn't receive even security fixes anymore.

**Comment by dmcbrn** [comment]
Version 8 was added yesterday but before I noticed your PR.

The `composer.json` should then bu updated to 

```
        "illuminate/support": "~6.0|~7.0|~8.0",
        "illuminate/database": "~6.0|~7.0|~8.0",
        "illuminate/mail": "~6.0|~7.0|~8.0",
        "illuminate/queue": "~6.0|~7.0|~8.0",
```

But I should probably test it out on v6 before that. Just to be 100% sure.
And then just add one final revision 6.0 until there's some breaking changes (which I doubt there would be in future). Not 100% about the `doctrine/dbal` dependency here. 

Just thinking at loud and logging for myself when I get back

**Pull request merged**
